name: Trigger auto deployment for container-app-4acdz7ck57fpc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-4acdz7ck57fpc-AutoDeployTrigger-104c28a0-dc94-44a9-b12d-f6d919f771c9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP4ACDZ7CK57FPC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP4ACDZ7CK57FPC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP4ACDZ7CK57FPC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry4acdz7ck57fpc.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP4ACDZ7CK57FPC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP4ACDZ7CK57FPC_REGISTRY_PASSWORD }}
          containerAppName: container-app-4acdz7ck57fpc
          resourceGroup: starshot-expresshello-manual
          imageToBuild: containerregistry4acdz7ck57fpc.azurecr.io/container-app-4acdz7ck57fpc:${{ github.sha }}
          


